<?php

namespace AppBundle\Repository;

/**
 * ApiTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
