<?php

namespace AppBundle\Repository;

/**
 * UsersGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
