AppBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        banner_url:
            type: string
            length: 255
    lifecycleCallbacks: {  }
