AppBundle\Entity\Projects:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProjectsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
